version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db-soccer
    environment:
      POSTGRES_DB: db_soccer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-soccer
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_soccer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
